nethserver-enterprise-groups.xml.in

Hide old reports from Software Center

---

nethserver-enterprise-groups.xml.in

Hide old hotspot

---

nethserver-enterprise-groups.xml.in

iso: add report and restore

---

nethserver-enterprise-groups.xml.in

Reports are inside dante package, not dedalo!

iso: replace dedalo with dante

---

nethserver-enterprise-groups.xml.in

comps. removed cockpit-dashboard optional package

---

nethserver-enterprise-groups.xml.in

https://github.com/NethServer/dev/issues/5912
https://github.com/NethServer/comps/pull/33

Add PHP SCL groups for Web server app

---

nethserver-enterprise-groups.xml.in

Reverts nethesis/comps#38
Obsoleted by
- https://github.com/NethServer/nethserver-rh-php72-php-fpm/pull/1
- https://github.com/NethServer/nethserver-rh-php71-php-fpm/pull/2
NethServer/dev#5912

Revert "Add PHP SCL groups for Web server app"

---

nethserver-enterprise-groups.xml.in
po/comps.pot
po/it.po

Everything is very stable right now :D

Remove beta tag from Cockpit and Dante

---

nethserver-enterprise-groups.xml.in
po/comps.pot
po/it.po

This group helps to update to the beta version of NethVoice 14 from nethesis-testing repo.

Add NethVoice 14 beta hidden group

---

nethserver-enterprise-groups.xml.in
po/comps.pot
po/it.po

Add nethserver-blacklist group

---

nethserver-enterprise-groups.xml.in

p3scan is officially deprecated
NethServer/dev#6117

Hide p3scan group

---

nethserver-enterprise-groups.xml.in
po/comps.pot
po/it.po

Nethesis/dev#5752
Add translations after merge of #42

Add nethserver-yomi

---

nethserver-enterprise-groups.xml.in
po/comps.pot
po/it.po

Add cockpit, remove httpd-admin

---

nethserver-enterprise-groups.xml.in

Add nethserver-netdata to ISO group

---

nethserver-enterprise-groups.xml.in
po/comps.pot
po/it.po

New nethvoice-report group

---

nethserver-enterprise-groups.xml.in

dahdi is again a nethvoice dependency
nethesis/dev#5937

Remove dahdi group

---

nethserver-enterprise-groups.xml.in

add nethserver-freepbx required by NethVoice
https://github.com/nethesis/dev/issues/6044

Add Nethvoice packages to fix removal

---

nethserver-enterprise-groups.xml.in

Cleanup all unused packages upon NethVoice removal
Nethesis/dev#6044

comps: add freepbx to nethvoice group

---

nethserver-enterprise-groups.xml.in

nethvoice-report: remove beta label

---

nethserver-enterprise-groups.xml.in
po/comps.pot
po/it.po

Add log manager agent

---

nethserver-enterprise-groups.xml.in

https://github.com/nethesis/dev/issues/6189

NethHotel as group instead of NethVoice optional package

---

nethserver-enterprise-groups.xml.in

Rename also existing package to easy the user choice

Add Flashstart Pro Plus

---

nethserver-enterprise-groups.xml.in

Display the migration package inside the UI
Card: https://trello.com/c/0SsoXN5P/172-release-checklist

comps: add nethserver-firewall-migration

---

nethserver-enterprise-groups.xml.in
po/comps.pot
po/it.po

As per Filippo request; wait stable release before merging.
See also https://github.com/NethServer/comps/pull/64

comps: remove Beta tag from nethserver-firewall-migration
